## Reading the data from database

In [1]:
import sqlite3
import pandas as pd
con=sqlite3.connect("eng_subtitles_database.db")
cursor=con.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
print(cursor.fetchall())

[('zipfiles',)]

In [2]:
cursor.execute("PRAGMA table_info('zipfiles')")
columns=cursor.fetchall()
print("The columns of the zipfiles table is:")
for col in columns:
    print(col[1])

The columns of the zipfiles table is:
num
name
content

In [3]:
df=pd.read_sql_query("""SELECT * FROM zipfiles""",con)
df.head()

,num,name,content
0,9180533,the.message.(1976).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x1c\xa9\x...
1,9180583,here.comes.the.grump.s01.e09.joltin.jack.in.bo...,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x17\xb9\x...
2,9180592,yumis.cells.s02.e13.episode.2.13.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00L\xb9\x99V...
3,9180594,yumis.cells.s02.e14.episode.2.14.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00U\xa9\x99V...
4,9180600,broker.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x001\xa9\x99V...

In [4]:
import zipfile
import io
cnt=0
def decode(binary_data):
    global cnt
    cnt+=1
    with io.BytesIO(binary_data) as f:
        with zipfile.ZipFile(f,'r') as zip_file:
            subtitle_content=zip_file.read(zip_file.namelist()[0])
    return subtitle_content.decode('latin-1')

In [5]:
df['file_content']=df['content'].apply(decode)
df.head()

,num,name,content,file_content
0,9180533,the.message.(1976).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x1c\xa9\x...,"1\r\n00:00:06,000 --> 00:00:12,074\r\nWatch an..."
1,9180583,here.comes.the.grump.s01.e09.joltin.jack.in.bo...,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x17\xb9\x...,"1\r\n00:00:29,359 --> 00:00:32,048\r\nAh! Ther..."
2,9180592,yumis.cells.s02.e13.episode.2.13.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00L\xb9\x99V...,"1\r\n00:00:53,200 --> 00:00:56,030\r\n<i>Yumi'..."
3,9180594,yumis.cells.s02.e14.episode.2.14.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00U\xa9\x99V...,"1\r\n00:00:06,000 --> 00:00:12,074\r\nWatch an..."
4,9180600,broker.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x001\xa9\x99V...,"ï»¿1\r\n00:00:06,000 --> 00:00:12,074\r\nWatch..."

In [6]:
no_of_rows=len(df.axes[0])
ids=[]
for i in range(1,no_of_rows+1):
    ids.append(i)
df['unique_id']=ids
df

,num,name,content,file_content,unique_id
0,9180533,the.message.(1976).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x1c\xa9\x...,"1\r\n00:00:06,000 --> 00:00:12,074\r\nWatch an...",1
1,9180583,here.comes.the.grump.s01.e09.joltin.jack.in.bo...,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x17\xb9\x...,"1\r\n00:00:29,359 --> 00:00:32,048\r\nAh! Ther...",2
2,9180592,yumis.cells.s02.e13.episode.2.13.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00L\xb9\x99V...,"1\r\n00:00:53,200 --> 00:00:56,030\r\n<i>Yumi'...",3
3,9180594,yumis.cells.s02.e14.episode.2.14.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00U\xa9\x99V...,"1\r\n00:00:06,000 --> 00:00:12,074\r\nWatch an...",4
4,9180600,broker.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x001\xa9\x99V...,"ï»¿1\r\n00:00:06,000 --> 00:00:12,074\r\nWatch...",5
...,...,...,...,...,...
82493,9521935,the.prophets.game.(2000).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\xb8\xa6\x...,"ï»¿1\r\n00:01:16,284 --> 00:01:19,537\r\nGod,\...",82494
82494,9521937,west.beirut.(1998).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x13\x97\x...,"1\r\n00:00:06,000 --> 00:00:12,074\r\napi.Open...",82495
82495,9521938,frankenstein.the.true.story.(1973).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00$\x97\x9aV...,"1\r\n00:00:01,001 --> 00:00:04,630\r\n(Dramati...",82496
82496,9521940,frankenstein.the.true.story.(1973).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x00\x97\x...,"1\r\n00:00:06,000 --> 00:00:12,074\r\nAdvertis...",82497
82497,9521941,zombie.island.massacre.(1984).eng.1cd,"b'PK\x03\x04\x14\x00\x00\x00\x08\x00,\x97\x9aV...","1\r\n00:00:01,919 --> 00:00:03,253\r\n(Sharp w...",82498

## Cleaning the Data

### Taking only 30% of the data

In [8]:
import re
import string

def clean(data):
    lower=data.lower()
    without_html=re.sub(r'<.*?>','',lower)
    pattern = r'\d+\r\n(\d{2}:\d{2}:\d{2},\d{3}) --> \d{2}:\d{2}:\d{2},\d{3}\r\n([\s\S]*?)\r\n\r\n'
    matches = re.findall(pattern, without_html)
    text = [re.sub(r'<\/?i>', '', match[1]) for match in matches]
    #remove punctuation
    cleaned_text = [" ".join(["".join([char for char in word if char not in string.punctuation]) for word in t.split()]) for t in text]
    result = " ".join(cleaned_text)
    return result

In [9]:
df1=df.head(24750)
df1

,num,name,content,file_content,unique_id
0,9180533,the.message.(1976).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x1c\xa9\x...,"1\r\n00:00:06,000 --> 00:00:12,074\r\nWatch an...",1
1,9180583,here.comes.the.grump.s01.e09.joltin.jack.in.bo...,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x17\xb9\x...,"1\r\n00:00:29,359 --> 00:00:32,048\r\nAh! Ther...",2
2,9180592,yumis.cells.s02.e13.episode.2.13.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00L\xb9\x99V...,"1\r\n00:00:53,200 --> 00:00:56,030\r\n<i>Yumi'...",3
3,9180594,yumis.cells.s02.e14.episode.2.14.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00U\xa9\x99V...,"1\r\n00:00:06,000 --> 00:00:12,074\r\nWatch an...",4
4,9180600,broker.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x001\xa9\x99V...,"ï»¿1\r\n00:00:06,000 --> 00:00:12,074\r\nWatch...",5
...,...,...,...,...,...
24745,9279493,scorpion.s04.e16.nerd.wind.fire.(2018).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\xa6\xa1\x...,"ï»¿1\r\n00:00:01,101 --> 00:00:04,367\r\n- WAL...",24746
24746,9279494,scorpion.s04.e17.dumbster.fire.(2018).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\\\xa1\x99...,"ï»¿1\r\n00:00:01,101 --> 00:00:04,071\r\n- WAL...",24747
24747,9279495,scorpion.s04.e18.dork.day.afternoon.(2018).eng...,b'PK\x03\x04\x14\x00\x00\x00\x08\x00;\xa1\x99V...,"ï»¿1\r\n00:00:02,002 --> 00:00:05,029\r\n- Kid...",24748
24748,9279496,scorpion.s04.e19.gator.done.(2018).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00l\xa1\x99V...,"ï»¿1\r\n00:00:01,101 --> 00:00:02,399\r\nWALTE...",24749
24749,9279497,scorpion.s04.e20.foul.balls.(2018).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00r\xa1\x99V...,"ï»¿1\r\n00:00:02,169 --> 00:00:04,468\r\nTOBY:...",24750

In [10]:
copy_df=df1.copy()

In [11]:
copy_df['Cleaned Text']=copy_df['file_content'].apply(clean)

In [13]:
copy_df

,num,name,content,file_content,unique_id,Cleaned Text
0,9180533,the.message.(1976).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x1c\xa9\x...,"1\r\n00:00:06,000 --> 00:00:12,074\r\nWatch an...",1,watch any video online with opensubtitles free...
1,9180583,here.comes.the.grump.s01.e09.joltin.jack.in.bo...,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x17\xb9\x...,"1\r\n00:00:29,359 --> 00:00:32,048\r\nAh! Ther...",2,ah theres princess dawn and terry with the blo...
2,9180592,yumis.cells.s02.e13.episode.2.13.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00L\xb9\x99V...,"1\r\n00:00:53,200 --> 00:00:56,030\r\n<i>Yumi'...",3,yumis cells 2 episode 36 extremely polite yumi...
3,9180594,yumis.cells.s02.e14.episode.2.14.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00U\xa9\x99V...,"1\r\n00:00:06,000 --> 00:00:12,074\r\nWatch an...",4,watch any video online with opensubtitles free...
4,9180600,broker.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x001\xa9\x99V...,"ï»¿1\r\n00:00:06,000 --> 00:00:12,074\r\nWatch...",5,watch any video online with opensubtitles free...
...,...,...,...,...,...,...
24745,9279493,scorpion.s04.e16.nerd.wind.fire.(2018).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\xa6\xa1\x...,"ï»¿1\r\n00:00:01,101 --> 00:00:04,367\r\n- WAL...",24746,walterpreviously on scorpion hey patty i mad...
24746,9279494,scorpion.s04.e17.dumbster.fire.(2018).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\\\xa1\x99...,"ï»¿1\r\n00:00:01,101 --> 00:00:04,071\r\n- WAL...",24747,walterpreviously on scorpion whats that thin...
24747,9279495,scorpion.s04.e18.dork.day.afternoon.(2018).eng...,b'PK\x03\x04\x14\x00\x00\x00\x08\x00;\xa1\x99V...,"ï»¿1\r\n00:00:02,002 --> 00:00:05,029\r\n- Kid...",24748,kid well run out of time well make it youll ...
24748,9279496,scorpion.s04.e19.gator.done.(2018).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00l\xa1\x99V...,"ï»¿1\r\n00:00:01,101 --> 00:00:02,399\r\nWALTE...",24749,walterpreviously on scorpion my entire school ...
24749,9279497,scorpion.s04.e20.foul.balls.(2018).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00r\xa1\x99V...,"ï»¿1\r\n00:00:02,169 --> 00:00:04,468\r\nTOBY:...",24750,toby this memo is an insult youve been offered...

In [14]:
def title_clean(title):
    new_title=title.replace("eng.1cd"," ").replace("."," ").strip()
    return new_title

In [15]:
copy_df['name']=copy_df["name"].apply(title_clean)

In [16]:
copy_df

,num,name,content,file_content,unique_id,Cleaned Text
0,9180533,the message (1976),b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x1c\xa9\x...,"1\r\n00:00:06,000 --> 00:00:12,074\r\nWatch an...",1,watch any video online with opensubtitles free...
1,9180583,here comes the grump s01 e09 joltin jack in bo...,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x17\xb9\x...,"1\r\n00:00:29,359 --> 00:00:32,048\r\nAh! Ther...",2,ah theres princess dawn and terry with the blo...
2,9180592,yumis cells s02 e13 episode 2 13 (2022),b'PK\x03\x04\x14\x00\x00\x00\x08\x00L\xb9\x99V...,"1\r\n00:00:53,200 --> 00:00:56,030\r\n<i>Yumi'...",3,yumis cells 2 episode 36 extremely polite yumi...
3,9180594,yumis cells s02 e14 episode 2 14 (2022),b'PK\x03\x04\x14\x00\x00\x00\x08\x00U\xa9\x99V...,"1\r\n00:00:06,000 --> 00:00:12,074\r\nWatch an...",4,watch any video online with opensubtitles free...
4,9180600,broker (2022),b'PK\x03\x04\x14\x00\x00\x00\x08\x001\xa9\x99V...,"ï»¿1\r\n00:00:06,000 --> 00:00:12,074\r\nWatch...",5,watch any video online with opensubtitles free...
...,...,...,...,...,...,...
24745,9279493,scorpion s04 e16 nerd wind fire (2018),b'PK\x03\x04\x14\x00\x00\x00\x08\x00\xa6\xa1\x...,"ï»¿1\r\n00:00:01,101 --> 00:00:04,367\r\n- WAL...",24746,walterpreviously on scorpion hey patty i mad...
24746,9279494,scorpion s04 e17 dumbster fire (2018),b'PK\x03\x04\x14\x00\x00\x00\x08\x00\\\xa1\x99...,"ï»¿1\r\n00:00:01,101 --> 00:00:04,071\r\n- WAL...",24747,walterpreviously on scorpion whats that thin...
24747,9279495,scorpion s04 e18 dork day afternoon (2018),b'PK\x03\x04\x14\x00\x00\x00\x08\x00;\xa1\x99V...,"ï»¿1\r\n00:00:02,002 --> 00:00:05,029\r\n- Kid...",24748,kid well run out of time well make it youll ...
24748,9279496,scorpion s04 e19 gator done (2018),b'PK\x03\x04\x14\x00\x00\x00\x08\x00l\xa1\x99V...,"ï»¿1\r\n00:00:01,101 --> 00:00:02,399\r\nWALTE...",24749,walterpreviously on scorpion my entire school ...
24749,9279497,scorpion s04 e20 foul balls (2018),b'PK\x03\x04\x14\x00\x00\x00\x08\x00r\xa1\x99V...,"ï»¿1\r\n00:00:02,169 --> 00:00:04,468\r\nTOBY:...",24750,toby this memo is an insult youve been offered...

### Chunking the data

In [17]:
import pandas as pd
def chunk_data(row,size=1500):
    data=row['Cleaned Text']
    chunks=[data[i:i+size] for i in range(0,len(data),size)]
    return pd.DataFrame({'name':[row['name']]*len(chunks),'Chunked Data':chunks})
result=pd.concat([chunk_data(i) for _, i in copy_df.iterrows()],ignore_index=True)
print(result)

                                      name  \
0                       the message (1976)
1                       the message (1976)
2                       the message (1976)
3                       the message (1976)
4                       the message (1976)
...                                    ...
427628  scorpion s04 e20 foul balls (2018)
427629  scorpion s04 e20 foul balls (2018)
427630  scorpion s04 e20 foul balls (2018)
427631  scorpion s04 e20 foul balls (2018)
427632  scorpion s04 e20 foul balls (2018)

                                             Chunked Data
0       watch any video online with opensubtitles free...
1       sts brought their idols and the images of thei...
2       he is 40 years old its unnatural with a rich w...
3       y in the shape of a man standing on the horizo...
4        but whilst im alive you will obey your father...
...                                                   ...
427628  t thing that you guys have no romantic feeling...
427629  ey where are you going well looks like kyles g...
427630  e all wearing the same shirts it shows were a ...
427631  at the snot out of it homeland player we got t...
427632   a backup plan with you i dont need one yes â...

[427633 rows x 2 columns]

In [25]:
result.to_csv("Chunked_Data.csv")